name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t missariahil/flask-hosting-platform:latest .

      - name: Push Docker image
        run: |
          docker push missariahil/flask-hosting-platform:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull missariahil/flask-hosting-platform:latest
            docker stop my-flask-app || true
            docker rm my-flask-app || true
            docker run -d -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock --name my-flask-app missariahil/flask-hosting-platform:latest
